import type { Scene } from "../types";
import { wash } from "../helpers";

/**
 * The original scenes. All copy is original: no trademarked characters, quotes
 * or artwork.
 */
export const CORE_SCENES: Scene[] = [
  {
    id: "classic",
    name: "Classic",
    group: "everyday",
    icon: "mail",
    accent: "#d4ff00",
    blurb: "A calm, neutral inbox. The default.",
    to: "alex@northwind.com",
    subject: "Following up on our call",
    greeting: "Hi Alex,",
    body: [
      "Thanks for making time today. I've attached the proposal we talked through. If it looks right on your side, I can have the next steps lined up by Friday.",
    ],
    closing: "Best,",
    bar: {
      light: "linear-gradient(180deg, #f6f7fb, #eceef5)",
      dark: "linear-gradient(180deg, #27272c, #1e1e22)",
    },
    barText: { light: "#6e7180", dark: "#a1a1aa" },
    dots: ["#d4d4d8", "#d4d4d8", "#d4d4d8"],
    stage: wash("212,255,0", 0.2, 0.1),
    fx: "none",
    fxColors: [],
  },
  {
    id: "pirate",
    name: "Pirate",
    group: "adventure",
    icon: "ship",
    accent: "#e8962e",
    blurb: "Swashbuckling captain energy: ahoy, treasure, doubloons.",
    to: "first.mate@blackwater.co",
    subject: "Treasure map attached",
    greeting: "Ahoy Alex,",
    body: [
      "The crew has read yer proposal and the cap'n be mighty pleased, worth its weight in doubloons. Let's parley over a strong pot of coffee this week.",
    ],
    closing: "Fair winds,",
    bar: {
      light: "linear-gradient(135deg, #7c4a1e, #c07a30)",
      dark: "linear-gradient(135deg, #3b2410, #7a4a1a)",
    },
    barText: { light: "#fff7e6", dark: "#ffe9bf" },
    dots: ["#ffd98a", "#f5b94a", "#e8962e"],
    stage: wash("232,150,46", 0.28, 0.18),
    fx: "embers",
    fxColors: ["#f5b94a", "#ffd98a", "#e8962e"],
    font: "'Pirata One', 'Palatino Linotype', Georgia, serif",
    backdrop: { file: "pirate.mp4", poster: "pirate.jpg", opacity: 0.22 },
  },
  {
    id: "bard",
    name: "Bard",
    group: "adventure",
    icon: "drama",
    accent: "#8b5cf6",
    blurb: "Theatrical and poetic: quills, verse and flourish.",
    to: "alex@globe-theatre.org",
    subject: "A most excellent proposal",
    greeting: "Hark, Alex!",
    body: [
      "I have perused thy proposal and found it most agreeable. Prithee, let us meet this week; a video call shall suffice in these modern times.",
    ],
    closing: "With quill in hand,",
    bar: {
      light: "linear-gradient(135deg, #5b21b6, #8b5cf6)",
      dark: "linear-gradient(135deg, #2e1065, #5b21b6)",
    },
    barText: { light: "#f5f3ff", dark: "#ddd6fe" },
    dots: ["#fbbf24", "#c4b5fd", "#a78bfa"],
    stage: wash("139,92,246", 0.24, 0.2),
    fx: "sparkles",
    fxColors: ["#c4b5fd", "#fbbf24", "#e9d5ff"],
    font: "'IM Fell English', 'Palatino Linotype', Georgia, serif",
    backdrop: { file: "bard.mp4", poster: "bard.jpg", opacity: 0.2 },
  },
  {
    id: "surf",
    name: "Surf",
    group: "everyday",
    icon: "waves",
    accent: "#06b6d4",
    blurb: "Relaxed beach-town vibes: waves, sunshine, good energy.",
    to: "alex@shoreline.co",
    subject: "Gnarly idea, let's sync",
    greeting: "Hey Alex!",
    body: [
      "Caught your proposal between sets and the numbers look stacked. Let's sync this week, any time after my morning session works. Mahalo!",
    ],
    closing: "Hang loose,",
    bar: {
      light: "linear-gradient(135deg, #0d9488, #06b6d4 50%, #f97316)",
      dark: "linear-gradient(135deg, #134e4a, #0e7490 50%, #c2410c)",
    },
    barText: { light: "#ffffff", dark: "#e0fbff" },
    dots: ["#ec4899", "#fbbf24", "#22d3ee"],
    stage: wash("6,182,212", 0.26, 0.18),
    fx: "bubbles",
    fxColors: ["#67e8f9", "#ffffff", "#5eead4"],
    font: "Pacifico, 'Trebuchet MS', cursive",
    backdrop: { file: "surf.mp4", poster: "surf.jpg", opacity: 0.24 },
  },
  {
    id: "noir",
    name: "Noir",
    group: "everyday",
    icon: "fedora",
    accent: "#71717a",
    blurb: "Black-and-white detective mood: rain, shadows, dry wit.",
    to: "alex@whitaker-files.com",
    subject: "Re: The Whitaker file",
    greeting: "Alex,",
    body: [
      "The report hit my desk at midnight. Rain on the window, coffee gone cold, and the numbers told a story I couldn't ignore. Meet me tomorrow. Bring the contract.",
    ],
    closing: "Yours in the shadows,",
    bar: {
      light: "linear-gradient(135deg, #18181b, #3f3f46)",
      dark: "linear-gradient(135deg, #09090b, #27272a)",
    },
    barText: { light: "#e4e4e7", dark: "#d4d4d8" },
    dots: ["#a1a1aa", "#71717a", "#52525b"],
    stage: {
      light: "radial-gradient(60% 55% at 50% 0%, rgba(63,63,70,0.22), transparent 70%)",
      dark: "radial-gradient(60% 55% at 50% 0%, rgba(161,161,170,0.12), transparent 70%)",
    },
    fx: "rain",
    fxColors: ["#a1a1aa", "#d4d4d8"],
  },
  {
    id: "cosmic",
    name: "Cosmic",
    group: "adventure",
    icon: "orbit",
    accent: "#6366f1",
    blurb: "Space-age and futuristic: mission control, stars, launch.",
    to: "alex@orbit.systems",
    subject: "Mission update: proposal approved",
    greeting: "Mission control, hi Alex,",
    body: [
      "Proposal received and reviewed. All systems nominal and the trajectory looks promising. Let's schedule a launch window this week.",
    ],
    closing: "Ad astra,",
    bar: {
      light: "linear-gradient(135deg, #0f172a, #4338ca)",
      dark: "linear-gradient(135deg, #020617, #312e81)",
    },
    barText: { light: "#e0e7ff", dark: "#c7d2fe" },
    dots: ["#67e8f9", "#a5b4fc", "#f0abfc"],
    stage: wash("99,102,241", 0.26, 0.22),
    fx: "stars",
    fxColors: ["#ffffff", "#a5b4fc", "#67e8f9"],
  },
];
